### PR TITLE
test noarch bld 

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin , please rerender

**Comment by ngam** [comment]
@conda-forge-admin , please rerender

**Comment by ngam** [comment]
@conda-forge-admin , please rerender

**Comment by ngam** [comment]
@conda-forge-admin , please rerender

**Comment by ngam** [comment]
@kinow @oliver-sanders @hjoliver 

Okay, the noarch build seems working. Happy to clean this up and then we can merge into main or something. Cool with you all? Could we make sure this noarch build is actually good to go?

Thanks!

```
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:


# To have conda build upload to anaconda.org automatically, use
# conda config --set anaconda_upload yes
anaconda upload \
    /home/conda/feedstock_root/build_artifacts/linux-64/cylc-flow-base-8.0b3-py39hf3d152e_1.tar.bz2 \
    /home/conda/feedstock_root/build_artifacts/noarch/cylc-flow-8.0b3-pyhad50eba_1.tar.bz2
anaconda_upload is not set.  Not uploading wheels: []

INFO :: The inputs making up the hashes for the built packages are as follows:
{
  "cylc-flow-8.0b3-pyhad50eba_1": {
    "recipe": {
      "channel_targets": "conda-forge main",
      "graphviz": "2.47",
      "python": "3.9.* *_cpython"
    }
  },
  "cylc-flow-base-8.0b3-py39hf3d152e_1": {
    "recipe": {
      "channel_targets": "conda-forge main",
      "python": "3.9.* *_cpython",
      "target_platform": "linux-64"
    }
  }
}
```

**Comment by ngam** [comment]
The windows build fails (as it would) but linux_64 and osx_64 both pass like before. The final noarch build is going to happen on a linux_64 machine, so we should be cleared. I will clean up the meta.yaml file for a final build

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@hjoliver @oliver-sanders 

converted this into noarch build for convenience and conserving resources. This makes it work with aarch64, etc.

build looks fine and it seems this could be merged. I will do additional testing offline to make sure all works as expected (building locally). Let me know if you've got any questions/comments. Thanks!

```
# To have conda build upload to anaconda.org automatically, use
# conda config --set anaconda_upload yes
anaconda upload \
    /home/conda/feedstock_root/build_artifacts/noarch/cylc-flow-base-8.0b3-pyh6c4a22f_1.tar.bz2 \
    /home/conda/feedstock_root/build_artifacts/noarch/cylc-flow-8.0b3-pyhad50eba_1.tar.bz2
anaconda_upload is not set.  Not uploading wheels: []

INFO :: The inputs making up the hashes for the built packages are as follows:
{
  "cylc-flow-8.0b3-pyhad50eba_1": {
    "recipe": {
      "channel_targets": "conda-forge main",
      "graphviz": "2.47",
      "python": "3.9.* *_cpython"
    }
  },
  "cylc-flow-base-8.0b3-pyh6c4a22f_1": {
    "recipe": {
      "channel_targets": "conda-forge main",
      "python": "3.9.* *_cpython"
    }
  }
}
```

**Comment by ngam** [comment]
closes #30

**Comment by ngam** [comment]
Note, from my prelim testing, this is fine but won't necessarily resolve on some OS. The problem is in the wildly restrictive dependencies in the upstream repo. Will likely need to relax those if a noarch build to be legitimately useful...

**Comment by oliver-sanders** [comment]
@ngam

Thanks for your interest!

> converted this into noarch build for convenience and conserving resources. This makes it work with aarch64, etc.

The [list of criterion for `noarch: python` packages](https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=noarch#noarch-python) includes "No skips except for python version".

Cylc Flow is unix only and will not work on other platforms, hence the skip presently in the recipe. As a result of this Cylc Flow does not qualify for `noarch`.

> The problem is in the wildly restrictive dependencies in the upstream repo

We've yet to encounter such issues, if you could tell us the dependencies that are causing you issues on your system we may be able to look into it.

**Comment by ngam** [comment]
> Cylc Flow is unix only and will not work on other platforms, hence the skip presently in the recipe. As a result of this Cylc Flow does not qualify for `noarch`.
> 

Ah! Makes sense now. Okay, let's close this pr and focus on explicit support for osx-arm64 and linux-aarch64 (could potentially also add ppc). I will follow up on the dependencies so that we can narrow it.

**Comment by oliver-sanders** [comment]
I'm dropping a question in to the Conda Forge Gitter in the hope they can advise a better way forward. We should be `noarch: python`, just in a way that somehow excludes Windows.

**Comment by ngam** [comment]
I think they might say you'd need to specify the other ones explicitly. I can help you implement all unix-like platforms once we see what's up with the deps. We may need some tweaking for the aarch64/arm64 though as not everything is supported

**Comment by ngam** [comment]
I have access to linux_aarch64 (via [multipass.run](https://multipass.run/)) and so I can test that pretty easily on my m1 mac

**Comment by oliver-sanders** [comment]
Apparently it's not an issue for a `noarch: python` package to have dependencies which don't resolve on all platforms. There are some virtual packages called `__unix` and `__win` which could do the trick.

**Comment by oliver-sanders** [comment]
https://docs.conda.io/projects/conda/en/master/user-guide/tasks/manage-virtual.html?highlight=__unix#managing-virtual-packages

**Pull request closed without merging**
