### PR TITLE
Prep 8.0b1 release.

### PR DESCRIPTION
**Pull request by hjoliver**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hjoliver** [comment]
@conda-forge-admin, please rerender

**Comment by hjoliver** [comment]
@conda-forge-admin, please rerender

**Review by kinow — APPROVED** [review]
Downloaded the file from PYPI to check the hash, and it looks good. +1

**Comment by hjoliver** [comment]
> Downloaded the file from PYPI to check the hash

Note you can view the hash without downloading it.

**Comment by kinow** [comment]
> > Downloaded the file from PYPI to check the hash
> 
> Note you can view the hash without downloading it.

Aaaahh!! That button on the right hand side! I thought that was for downloading (never read the text) :laughing: thanks!

**Comment by hjoliver** [comment]
I don't think this needs a 2nd review.

**Pull request merged**
